name: fixify
region: nyc
services:
- name: fixify
  environment_slug: python
  github:
    repo: adeshpande03/fixify
    branch: main
  build_command: apt-get update && apt-get install -y ffmpeg
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
